Database:
  DBType: mysql
  UserName: root
  Password: root
  Host: 127.0.0.1:3306
  DBName: gin_gorm_obj
  Charset: utf8mb4
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
  Loc: Local
Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60